### ISSUE TITLE
how put token dc

### ISSUE THREAD

**Issue by elainasan1** [prometheus-lua/Prometheus-discord-bot#3]
where to put token

**Comment by elainasan1** [comment]
how to run iam always error in dotenv/config

**Comment by n1kzittxe** [comment]
create .env file

**Comment by levno-710** [comment]
You have to define the `DISCORD_TOKEN` environment variable.
This will automatically load variables from a .env file.
You can create a .env file with the following content:
```.env
DISCORD_TOKEN=<YOUR-TOKEN>
```
